### ISSUE TITLE
Can't edit cards

### ISSUE THREAD

**Issue by Terrance113** [MKT-Playbook/Hub#34] opened 2023-04-21 16:54 UTC
I can't edit the card for the new stuff in the tour. 

![IMG_8507](https://user-images.githubusercontent.com/123432737/233692141-5ae007dc-8f60-42f5-b25e-81679c2c9703.png)

**Comment by TitusPosiadly** [comment] 2023-04-21 22:42
Hey, thanks for the bug report.

Are you using more than one device? 
Also, could you check what your main device is set as?
_(Go into the settings and locate „Main Device“ under the „App Settings“ section)_

If it doesn’t say „This Device“ in parenthesis after the device name tap on the name and tap on the button „Set as main device“ that should now be visible. Now close and open your app again and everything should work as usual.

Let me know if you are still having issues after trying this.

**Comment by Terrance113** [comment] 2023-04-21 22:45
No, just my iPad since my phone is an android.

**Comment by TitusPosiadly** [comment] 2023-04-21 23:02
Could you check if your device is set as the main device?
(Go into the settings and locate „Main Device“ under the „App Settings“ section)

If it doesn’t say „This Device“ in parenthesis after the device name tap on the name and tap on the button „Set as main device“ that should now be visible. Now close and open your app again and everything should work as usual.

**Comment by Terrance113** [comment] 2023-04-21 23:10
No, it didn't. It is the main device,  but it didn't do anything. It worked
last tour when i imported Poochy and the other stuff that debuted. But now
it's not.

**Comment by TitusPosiadly** [comment] 2023-04-21 23:13
Hmm, have you tried to force close the app and open it again? New cards will only be added automatically on the app start.

**Comment by Terrance113** [comment] 2023-04-21 23:19
This showed up when i did.

**Comment by TitusPosiadly** [comment] 2023-04-21 23:25
What app version are you using right now?

Also, I think the image didn't make it through. Might have to add it directly on GitHub or just send me an email directly to info@mkt-playbook.com

**Comment by Terrance113** [comment] 2023-04-21 23:27
NOW it works. I had to give the app a tip too.

**Comment by TitusPosiadly** [comment] 2023-04-21 23:29
Huh? Hahaha very strange. Well, at least it works now. Could you still send the image from before?

**Comment by Terrance113** [comment] 2023-04-21 23:33
Just did.

**Comment by TitusPosiadly** [comment] 2023-04-21 23:36
Did you by any chance just update the app?

**Comment by Terrance113** [comment] 2023-04-21 23:37
I don't know.

**Comment by TitusPosiadly** [comment] 2023-04-21 23:44
Hmm, something is definitely not right. For now, we might just have to keep an eye on it and come back to it if anything else strange happens. Oh, you are in the beta test, right? Could you send me your logs as an email also to info@mkt-playbook.com? (Go into the settings, scroll down, and tap on "Export logs")

**Comment by Terrance113** [comment] 2023-04-22 01:01
I lost the beta test when I uninstalled the app, so I don't have any logs...

**Comment by TitusPosiadly** [comment] 2023-04-22 01:07
That's probably the reason for all the unexpected behavior. Downgrading from a newer to an older version can cause a number of issues. You should be able to download the beta again though. Either use the link in the invite again or download the newest version from the TestFlight app.

I'm gonna close the issue for now. Let me know if you have any more issues or if you need anything else.

**Closed as completed by TitusPosiadly** 2023-04-22 01:07 UTC
